### ISSUE TITLE
Error: plexConfigs list is empty

### ISSUE THREAD

**Issue by ThomasMacy** [Phineas05/discord-rich-presence-plex#11]
![unknown](https://user-images.githubusercontent.com/38705354/47292045-24c77780-d606-11e8-8164-636528d6500a.png)
I get this error when opening the script, i have put in the correct name, password, token etc. 
Infact, it doesnt matter what i put in i just get this error.

**Comment by Phineas05** [comment]
Does the config line begin with a hash? If so, the line is considered a comment in Python and isn't interpreted.

**Comment by ThomasMacy** [comment]
Yea my bad, it was, but now im getting another issue, its saying invalid token, reconnecting, failed to connect etc, this is the correct place to get the token right? its highlighted in blue.
![unknown 1](https://user-images.githubusercontent.com/38705354/47292714-2d20b200-d608-11e8-8015-cb0acbd572a5.png)

**Comment by Phineas05** [comment]
Yes, that should be the right one. Verify that the token you supplied in the script matches it perfectly.

**Comment by ThomasMacy** [comment]
It matches it perfectly, This is what it looks right now.
![unknown 2](https://user-images.githubusercontent.com/38705354/47293533-b1743480-d60a-11e8-88be-6568dffc0470.png)

**Comment by Phineas05** [comment]
Not sure why it wouldn't be working then. Try using your e-mail instead of your username. Also, either your password or a token is enough for it to log in, doesn't require both. Remove the token field completely to make it log in using the password.

**Comment by ThomasMacy** [comment]
The code seems to work now after removing the token field. But now it doesnt show up on discord at all.

**Comment by ThomasMacy** [comment]
It now says "unathorized" in the code after recieving session id update.

**Comment by Phineas05** [comment]
Could you upload a screenshot of the console? If the script isn't receiving alerts from Plex, that's an issue caused by the latest version of websocket-client which breaks the plexapi module's alert listener. Downgrade websocket-client to version 0.48.0 by running `pip install websocket-client==0.48.0`.

**Comment by ThomasMacy** [comment]
Still the same error.
![capture](https://user-images.githubusercontent.com/38705354/47295301-9f48c500-d60f-11e8-8f5d-de828dec9fd3.PNG)

**Comment by Phineas05** [comment]
Does the account you're logging into own that Plex server? If not, it won't work. Plex only sends alerts to the account that owns the Plex server.

**Comment by ThomasMacy** [comment]
Yea i dont own the Plex Server. The other script SwiftPanda16 made works without being the server owner though.

**Comment by Phineas05** [comment]
Looks like the behavior has changed since the last time I tried it with an account that didn't own the server. I've updated the script to support non-owner accounts. Update your copy and let me know if it works.

**Comment by ThomasMacy** [comment]
It works now! Thanks so much, it would be nice if there was some way to make the script start whenever you opened plex though.

**Comment by Phineas05** [comment]
The rich presence is only displayed while media is playing and is hidden after 5 seconds of inactivity after the media stops, so you can have the script running at all times. You can create a shortcut with the target `pythonw <path to script>` and place it in the `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup` folder to have it start automatically when you log into your Windows user account.
