### ISSUE TITLE
Restrict libraries

### ISSUE THREAD

**Issue by WikiCopter** [Phineas05/discord-rich-presence-plex#14]
Would it be possible to have the script only listen for playback events from certain libraries and/or reject playback events from blacklisted libraries?

**Comment by Phineas05** [comment]
I've added `blacklistedLibraries` and `whitelistedLibraries` as optional parameters for the `plexConfig` class. You can pass along the names of the libraries to blacklist/whitelist as a list while creating an instance of the class. Example:
```python
plexConfigs = [
	plexConfig(serverName = "ABC", username = "abc", password = "abc", whitelistedLibraries = ["Movies", "TV Shows"])
]
```

**Comment by WikiCopter** [comment]
Awesome, that's exactly what I was looking for. Thanks!
