### ISSUE TITLE
Show duration line

### ISSUE THREAD

**Issue by mclarence** [Phineas05/discord-rich-presence-plex#15]
<img width="236" alt="screen shot 2018-12-11 at 4 33 36 pm" src="https://user-images.githubusercontent.com/25338414/49780542-11619e80-fd63-11e8-8f84-97dcc04dd911.png">
Looking at the screenshot above, the minutes and seconds seem to be the wrong order. Sometimes it is in the correct order and sometimes its not.

**Comment by Phineas05** [comment]
Which version of Python are you running?

**Comment by mclarence** [comment]
I was running python 3.5.3. I then proceeded to update to 3.6.7 via pyenv now the script does not detect that I am playing something on plex. It says it is logged in and connected to the plex media server. I switch back to 3.5.3 and it works.

Here is the output from the script:
`[11:36:30 AM] [Hetzner/05fb1] Logged in as Plex User "mclarence_"
[11:36:30 AM] [Hetzner/05fb1] Connected to Plex Media Server "Hetzner"
[11:36:30 AM] [Hetzner/05fb1] Listening for PlaySessionStateNotification alerts from user "mclarence_"
[11:37:30 AM] [Hetzner/05fb1] Request for clients list to check connection: []`

**Comment by Phineas05** [comment]
The time display issue is caused due to Python versions prior to 3.6 not preserving dictionary key insertion order. As for it not detecting what you're playing, can you check if the websocket-client module's version is 0.48.0? (`pip show websocket-client`)

**Comment by mclarence** [comment]
Thanks, that was the issue. I forgot to install version 0.48.0 of that module when I updated to 3.6.7. Now the show duration appears to be showing correctly.
