### ISSUE TITLE
Working on "cloud"

### ISSUE THREAD

**Issue by NBSDEVApp** [Phineas05/discord-rich-presence-plex#17]
Hi,
I have my plex on a bytesized-hosting server, do you think the plex rich presence can work? Or its only for local network plex?
Thanks and nice work 👍

**Comment by Phineas05** [comment]
It doesn't matter where the Plex server is hosted. The script has to be run on same machine as your Discord client.

**Comment by NBSDEVApp** [comment]
okay, I just need to execute with python windows?

**Comment by Phineas05** [comment]
Yeah.

**Comment by NBSDEVApp** [comment]
Thanks work very good ;)
