### ISSUE TITLE
installation trouble

### ISSUE THREAD

**Issue by Shadow19231** [phineas05/discord-rich-presence-plex#20]
Hello! i am new to python so just installing that was a hassle. i was wondering if this script works for  plex media _player_ or just plex media server.

Right now it continuously mentions that it is listening and ready, but i can't seem to find a way to trigger it to work. 

any help would be great, thanks!

**Comment by Phineas05** [comment]
The script connects to your Plex Media Server and listens for alerts. You can use any client, including Plex Media Player, to play something from this server. The script then communicates with Discord and sets your rich presence. The script has to be running on the same machine as your Discord client. If it's still not working, could you send me a screenshot of the console output?

**Comment by Shadow19231** [comment]
> The script connects to your Plex Media Server and listens for alerts. You can use any client, including Plex Media Player, to play something from this server. The script then communicates with Discord and sets your rich presence. The script has to be running on the same machine as your Discord client. If it's still not working, could you send me a screenshot of the console output?

I see so i install this on the server. 
Does discord update globally for me? Say i was watching on a different computer with the same discord account, would both clients show "one Piece" in example?

**Comment by Phineas05** [comment]
> I see so i install this on the server.

You don't need to install it alongside the server. It has to be on the same machine as your Discord client.

> Does discord update globally for me? Say i was watching on a different computer with the same discord account, would both clients show "one Piece" in example?

Haven't tried it but I think it'll work fine.

**Comment by jacobmix** [comment]
Should be running on the PC with Discord. It'll connect to your Plex server, and just show what anyone is playing. If you share you server with others you can set `listenForUser = "PlexUserNameHere"` to only show what you're watching.

Here's all the instructions step, by step:

> Install Python 3 if not already installed:
> https://www.python.org/downloads/windows/
>
> Get pip:
> curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
> py -3 get-pip.py
> py -3 -m pip install --upgrade pip
> 
> Install Discord Rich Presence for Plex Requirements:
> py -3 -m pip install plexapi
> py -3 -m pip install websocket-client==0.48.0
> 
> Download or clone: https://github.com/Phineas05/discord-rich-presence-plex
> After Extracting the contents from GitHub. Add your configuration(s) into the plexConfigs list in the discordRichPresencePlex.py file on line 30.
> 
> Example:
> 
> plexConfigs = [
>     plexConfig(serverName = "PlexServerNameHere", username = "PlexUserNameOrEmailHere", password = "PlexPasswordHere"), blacklistedLibraries = ["Extras", "Music"]),
>     plexConfig(serverName = "PlexServerNameHere", username = "PlexUserNameOrEmailHere", token = "ServerTokenHere", listenForUser = "PlexUserHere")
> ]
> 
> token (not required if password is set) - A [X-Plex-Token](https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token) associated with the above account. In some cases, `myPlexAccessToken` from Plex Web App's HTML5 Local Storage must be used. To retrieve this token in Google Chrome, open Plex Web App, press F12, go to "Application", expand "Local Storage" and select the relevant entry. Ignores `password` if set.
> 
> listenForUser (optional) - The script will respond to alerts originating only from this username. Defaults to `username` if not set.
> 
> More infor in the README.md
> 
> 
> Then start it with:
> py -3 -m discordRichPresencePlex.py
> 
> You can always make a bat file to start it instead.
> Just place these two lines in a bat file at the same location as discordRichPresencePlex.py:
> cd /d "%~dp0"
> py -3 -m discordRichPresencePlex.py
>
> cd /d "%~dp0" just points to bat file to the location it got opened in.
> If you for some reason wanna run it as admin you can make a shortcut of the bat, and set the shortcut to run as admin.

**Comment by noah1gamble** [comment]
> Should be running on the PC with Discord. It'll connect to your Plex server, and just show what anyone is playing. If you share you server with others you can set `listenForUser = "PlexUserNameHere"` to only show what you're watching.
> 
> Here's all the instructions step, by step for Windows 64-bit. (Mostly the same for others):
> 
> > Install Python 3 if not already installed:
> > https://www.python.org/downloads/windows/
> > Click `Latest Python 3 Release - Python X.X.X`
> > Then on the page scroll down, and get `Windows x86-64 executable installer`.
> > Run the installer, and make sure `Add Python X.X to PATH` is ticked on when installing.
> > Get pip (use CMD or PowerShell to enter commands):
> > `curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`
> > `py -3 get-pip.py`
> > `py -3 -m pip install --upgrade pip`
> > Install Discord Rich Presence for Plex Requirements:
> > `py -3 -m pip install plexapi`
> > `py -3 -m pip install websocket-client==0.48.0`
> > Download or clone: https://github.com/Phineas05/discord-rich-presence-plex
> > After Extracting the contents from GitHub. Add your configuration(s) into the plexConfigs list in the discordRichPresencePlex.py file on line 30.
> > Example of two servers. One using username, password, and library blacklist.
> > Another using server token, and listen for user:
> > plexConfigs = [
> > plexConfig(serverName = "`PlexServerNameHere`", username = "`PlexUserNameOrEmailHere`", password = "`PlexPasswordHere`", blacklistedLibraries = ["`UnwantedLibraryNameHere`", "`Extras`", "`Music`"])`,`
> > plexConfig(serverName = "`PlexServerNameHere`", username = "`PlexUserNameOrEmailHere`", token = "`ServerTokenHere`", listenForUser = "`PlexUserNameHere`")
> > ]
> > token (not required if password is set) - A [X-Plex-Token](https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token) associated with the above account. In some cases, `myPlexAccessToken` from Plex Web App's HTML5 Local Storage must be used. To retrieve this token in Google Chrome, open Plex Web App, press F12, go to "Application", expand "Local Storage" and select the relevant entry. Ignores `password` if set.
> > listenForUser (optional) - The script will respond to alerts originating only from this username. Defaults to `username` if not set.
> > blacklistedLibraries (list, optional) - Alerts originating from blacklisted libraries are ignored.
> > More info in the README.md
> > Then start it with:
> > `py -3 -m discordRichPresencePlex.py`
> > You can always make a bat file to start it instead.
> > Just place these two lines in a bat file at the same location as discordRichPresencePlex.py:
> > `cd /d "%~dp0"`
> > `py -3 -m discordRichPresencePlex.py`
> > `cd /d "%~dp0"` just points to bat file to the folder location it's in.
> > If you for some reason wanna run it as admin you can make a shortcut of the bat, and set the shortcut to run as admin.
> 
> Note: You have to have enable Game Activity in Discord User Settings, and actually play something from the Plex server for it to show. Shouldn't matter if it's in a browser or the Plex Media Player.
> 
> Also if you can't use Curl, make sure Windows is up to date or download [GitForWindows](https://gitforwindows.org/).
> Then use Git BASH for the command. Else you can manually get [get-pip.py](https://bootstrap.pypa.io/get-pip.py) with Ctrl+S in you browser.
> it's recommended you use [Notepad++](https://notepad-plus-plus.org/downloads/) to edit discordRichPresencePlex.py instead of regular Notepad.
> 
> If you have issues try running it as administrator to see if that fixes it.
> You can also download, and run [Rapid Environment Editor](https://www.rapidee.com/en/download) as Admin.
> See if your system environment variable PATH has any issues or duplicates.
> Else try uninstalling Python (all versions) and start over from the start.
> Also if you failed to add the path to Python when it installed you can do it manually or with REE.
> To manually add to PATH run `sysdm.cpl`>Advanced tab>Environment Variables>Under System vars
> find, and click `Path`. Then "Edit", and paste the Python path between others with `;` separating them.
> Python should be installed here if not changed: `%LocalAppData%l\Programs\Python\PythonXX` (XX=Ver)
> 
> If you've tried the script before. Completely clean out the site-packages dir and reinstalling the dependencies or start over fresh.

You're an absolute legend, I put this together in about 10 minutes with your guide.

![image](https://user-images.githubusercontent.com/11571144/90339598-d136d280-dfbf-11ea-8daf-77e34b10f613.png)

**Comment by phineas05** [comment]
Closing this issue as there is no response from the author for a long time after solutions were posted. Feel free to re-open if you still need help.
