### ISSUE TITLE
[REQUEST] Adjusting the title.

### ISSUE THREAD

**Issue by crimzind** [phineas05/discord-rich-presence-plex#28]
First, appreciate the script. Thank you.
Second, I was wondering if there was anyway I could adjust the text that shows in Discord. As is, it shows "Playing Plex". I was wondering if there's anyway I could substitute the word Plex for text of my choosing, or append additional text to it.

**Comment by titizaki** [comment]
I'd like to add my wish to this request.
I tried to fiddle around with the code by adding a "name" key to the activity dictionary, but that doesn't seem to work (I have no experience with Rich Presence).
Thanks for your attention.

**Comment by JoshTheBlack** [comment]
I would also like to be able to substitute "Plex" with another word.

**Comment by phineas05** [comment]
"Plex" is the name I've given to the application I registered on the Discord Developer Portal to obtain a client ID for the functioning of the script. Unfortunately, the rich presence API does not provide any way to change this dynamically.
