### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by thewillwilson** [Phineas05/discord-rich-presence-plex#3]
Is it possible to have a progress bar for the playback, like seen in this screenshot
![image](https://user-images.githubusercontent.com/6631206/38168200-d66b3554-353d-11e8-9ade-3998b9209fdf.png)

**Comment by Phineas05** [comment]
I've come across this before and tried to implement it by sending the end timestamp but unfortunately it displays only the time left instead of a progress bar. Must have been changed in a Discord update.
