### ISSUE TITLE
[enhancement] Adding "Watching" state instead of "Playing"

### ISSUE THREAD

**Issue by Ma145** [phineas05/discord-rich-presence-plex#33]
<img width="187" alt="Playing" src="https://user-images.githubusercontent.com/70784410/109895673-5dfc6180-7c6e-11eb-95fb-e2eecf00030e.PNG">

A nice feature would be instead of showing "Playing" ("Jogando" in Portuguese. My Discord is in Portuguese in the image above) show "Watching".
Thanks for the app, amazing job <3

**Comment by makesey** [comment]
I don't think that is possible. Discord Rich Presence was made for games, and I think that "Playing" refers to playing a game and is a fixed value which can't be changed

**Comment by Ma145** [comment]
![unnamed (1)](https://user-images.githubusercontent.com/70784410/109900738-9c961a00-7c76-11eb-97d6-d25d142398a2.jpg)
It might be possible to do something like the [Deezer Discord Integration](https://chrome.google.com/webstore/detail/deezer-discord-integratio/gpmnalhimebpjhilkifcaadejhmogaok) extension ? [Github](https://github.com/AdrienC/discord-deezer-chrome)

**Comment by phineas05** [comment]
This is not possible using the allowed methods ([RPC](https://discord.com/developers/docs/topics/rpc) /  [GameSDK](https://discord.com/developers/docs/game-sdk/sdk-starter-guide)) provided by Discord for setting Rich Presence.

It can be done by sending [Gateway Presence Updates](https://discord.com/developers/docs/topics/gateway#update-presence-gateway-presence-update-structure) directly to the [Discord WebSocket Gateway](https://discord.com/developers/docs/topics/gateway), which is what that Deezer extension seems to be doing, but using the gateway in third-party applications for non-bot accounts would fall under [self-botting](https://support.discord.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-) which is forbidden by Discord.

**Comment by apoapostolov** [comment]
I see; thanks for the answer.

**Comment by phin05** [comment]
Discord allows changing the activity type now. Implemented in [v2.8.0](https://github.com/phin05/discord-rich-presence-plex/releases/tag/v2.8.0).
