### ISSUE TITLE
[REQUEST] Show album cover as icon instead of the PleX logo when playing music

### ISSUE THREAD

**Issue by Jabster28** [phineas05/discord-rich-presence-plex#34]
Title.

**Comment by Visual917** [comment]
That isn't possible due to how Discord's API works.

**Comment by Jabster28** [comment]
@Visual917 Could you elaborate on that? Is the icon statically set from the Discord Developer Portal or something?

**Comment by Visual917** [comment]
> @Visual917 Could you elaborate on that? Is the icon statically set from the Discord Developer Portal or somet

Yes, also there is a 50 icon limit. Only Spotify has the API for that currently. So it is special/private.

**Comment by Jabster28** [comment]
Ah, that's a shame. No reason to keep this open, then.

**Comment by phineas05** [comment]
This feature has been implemented vide commit https://github.com/phineas05/discord-rich-presence-plex/commit/a40dbb45e8391b8b0b1c849e7610b81eded58414.

Refer to the [README](https://github.com/phineas05/discord-rich-presence-plex/blob/master/README.md) for instructions.

**Comment by Jabster28** [comment]
oh neat, thanks!
