### ISSUE TITLE
IPC set_activity fails if length of episode is more than 128 characters

### ISSUE THREAD

**Issue by Jabster28** [phineas05/discord-rich-presence-plex#35]
Title. Maybe some truncation should take place?

**Comment by BrutuZ** [comment]
https://github.com/Phineas05/discord-rich-presence-plex/blob/7a500aee4890eb17c131b36b49d2577df7cf223f/discordRichPresencePlex.py#L317-L326
```diff
	activity = {
-		"details": title,
-		"state": extra,
+		"details": title[:128],
+		"state": extra[:128],
 		"assets": { 
 			"large_text": largeText, 
 			"large_image": "logo", 
 			"small_text": state.capitalize(), 
 			"small_image": state 
 		}, 
 	} 
```

**Comment by phineas05** [comment]
The fix from the previous comment has been implemented in the recent commits to this project.
