### ISSUE TITLE
Stuck on  "Request for clients list to check connection"

### ISSUE THREAD

**Issue by itslino** [phineas05/discord-rich-presence-plex#36]
Usually as soon as I play media the script would take over and do its thing but lately it just stays like that.
Constantly loading a new row of " Request for clients list to check connection "

I even tried getting a new token but nothing seems to fix it.

**Comment by jacobmix** [comment]
Not sure if anything changed on the Plex side. But now it works again.

**Comment by Keiyuu** [comment]
I'm having the same issue now. Haven't been using it for a few weeks and now it doesn't work anymore.
Is this tool still being worked on? It's the best by far and I would love to keep using it.
Same error: " Request for clients list to check connection"

Can this be fixed? I would switch to the tool linked above but I don't like how it displays stuff and it shows less info as well...

**Comment by phineas05** [comment]
Closing this as the issue appears to be solved. Feel free to re-open if not.
