### ISSUE TITLE
Running on remote server

### ISSUE THREAD

**Issue by ronilaukkarinen** [Phineas05/discord-rich-presence-plex#38]
I have Discord client on my PC but Plex is running on different Linux server. The script runs just fine but it throws `[HANDSHAKE] [Errno 2] No such file or directory` as the Linux doesn't have Discord installed (why would it on a headless server?)

Any tips on how to get this working on remote server?

**Comment by jacobmix** [comment]
Has to be running on the same computer as Discord.

**Comment by ronilaukkarinen** [comment]
What if I want it to always send the Discord presence regardless of device. Say if I use Android and Chromecast? Not possible in any way?

**Comment by jacobmix** [comment]
Keep Discord logged in on your computer, and keep the program running. It'll always show when your Plex account is watching something.

**Comment by ronilaukkarinen** [comment]
I decided to install this all the computers I use Discord with and then just run it on background when the computers and discords are open. Thanks.
