### ISSUE TITLE
picture upload failing with nonetype error

### ISSUE THREAD

**Issue by iurirolho** [phineas05/discord-rich-presence-plex#44]
![image](https://user-images.githubusercontent.com/20928051/173899364-3b087b88-a822-49aa-b895-ab993422ad15.png)
"[15-06-2022 07:26:55 PM] [ERROR] [Iuri's Private/Trusted Friends Only Plex Server/E73CE] An unexpected error occured in the alert handler
Traceback (most recent call last):
  File "d:\discord rich presence py\services\PlexAlertListener.py", line 211, in handlePlexAlert
    thumbUrl = uploadImage(self.server.url(thumb, True))
  File "C:\Users\iurim\AppData\Local\Programs\Python\Python310\lib\site-packages\plexapi\server.py", line 796, in url
    delim = '&' if '?' in key else '?'
TypeError: argument of type 'NoneType' is not iterable"
anything you need in order to figure what is causing this, if so am i say it, i been using this for long, great script

**Comment by phineas05** [comment]
I've pushed a fix for this error. Update your copy of the script.
