### ISSUE TITLE
SSL Certificate Verify Failed on Mac

### ISSUE THREAD

**Issue by TubeBoyJimmy** [phineas05/discord-rich-presence-plex#45]
Hi All,

I got SSL Certificate Verify Failed on my Mac.
I already have installed python 3.10 and all modules required and follow the configuration steps to setup config.json, same config.json works on my PC.
Here is the debug log:

> [26-06-2022 11:16:35 PM] [INFO] Discord Rich Presence for Plex - v2.2.4
> [26-06-2022 11:16:35 PM] [INFO] [My-NAS/A821F] Signing into Plex
> [26-06-2022 11:16:36 PM] [INFO] [My-NAS/A821F] Signed in as Plex user "User"
> [26-06-2022 11:16:36 PM] [INFO] [My-NAS/A821F] Connecting to Plex Media Server "My-NAS"
> [26-06-2022 11:16:41 PM] [INFO] [My-NAS/A821F] Connected to Plex Media Server "My-NAS"
> [26-06-2022 11:16:41 PM] [INFO] [My-NAS/A821F] Listening for alerts from user "User"
> [26-06-2022 11:16:41 PM] [ERROR] [My-NAS/A821F] Connection to Plex lost: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
> [26-06-2022 11:16:41 PM] [DEBUG] Attempt to disconnect Discord IPC Pipe while not connected
> [26-06-2022 11:16:41 PM] [INFO] [My-NAS/A821F] Stopped listening for alerts
> [26-06-2022 11:16:41 PM] [ERROR] [My-NAS/A821F] Reconnecting

**Comment by phineas05** [comment]
Refer to https://github.com/phineas05/discord-rich-presence-plex/issues/41.
