### ISSUE TITLE
Presence does not clear on video ending or closed

### ISSUE THREAD

**Issue by Krarche** [Phineas05/discord-rich-presence-plex#5]
The presence isn't correctly cleared when a video is either manually closed, or if the video is normally ending and hangs until Discord is closed.

**Comment by Phineas05** [comment]
Worked fine last time I checked but I just tested it and it's broken. Something must have changed on Discord's end. I'll look into it.

**Comment by Phineas05** [comment]
Update your copy of the script and let me know if it's fixed.

**Comment by Krarche** [comment]
Seems to work fine now ! It struggles a bit to update the presence when doing multiple actions rapidly (pause then quit for example) but I guess that's normal.

**Comment by Phineas05** [comment]
[This page](https://discordapp.com/developers/docs/rich-presence/how-to#updating-presence) says that it has a rate limit of one update per 15 seconds. As for stopping/quitting, it should clear the rich presence after 5 seconds if nothing else starts playing.
