### ISSUE TITLE
[FEATURE REQUEST] Add Optional Buttons

### ISSUE THREAD

**Issue by zluckytraveler** [phineas05/discord-rich-presence-plex#50]
**FEATURE REQUEST**

It would be nice if there was an _option_ to add buttons (configurable in `config.json` file), specifically two different buttons. One button which would be used for the current media that is being streamed supplying the media link to the users choice of IMDb, TMDB, or Trakt, by using an api key similar to Imgur. The secondary button would be used for any url link the user wishes to direct to.

Another rich presence application called [Perplex](https://github.com/EthanC/Perplex) has a very similar feature, however the buttons are not customizable unless you edit parts of the code, additionally their application will crash if it's left running for too long. I really prefer to use this application due to the community and the creator who maintains this project still.

Hope this gets approved!

**Comment by phineas05** [comment]
Implemented vide commit e8cd2c04dcb98a4f82726e3ed6f1a36c72d18901.

Refer to the [README](https://github.com/phineas05/discord-rich-presence-plex/blob/master/README.md) for instructions.

**Comment by zluckytraveler** [comment]
Woohoo! You are the best!

**Comment by zluckytraveler** [comment]
@phineas05 Just an fyi, the button clicks are only unresponsive to the account owner on desktop client. They will work on mobile app and browser. Just incase you want to revise the readme to include this information.

**Comment by phineas05** [comment]
They do seem to respond on clients other than the desktop client receiving Rich Presence updates. However, until restarted/reloaded, those clients aren't updating the button URLs when the media being played changes and causes the button URLs to change.
