### ISSUE TITLE
[Question] Change the position of total time

### ISSUE THREAD

**Issue by zeroquinc** [phineas05/discord-rich-presence-plex#54]
First of all thanks for this great piece of software.

I'm talking about this part.

![image](https://user-images.githubusercontent.com/39315068/188503574-8b89b71c-ce85-4f04-b097-707d694d23c4.png)

For me it would make much more sense to put it on the line below it. Is this possible?

So it shows 1h25s - 04:32 elapsed.

**Comment by phineas05** [comment]
That does make more sense but unfortunately Discord has dedicated that line for solely displaying the time elapsed/remaining and doesn't provide any way to add anything else to that line.

**Comment by zeroquinc** [comment]
> That does make more sense but unfortunately Discord has dedicated that line for solely displaying the time elapsed/remaining (calculated and displayed by the client based on timestamps) and doesn't provide any way to add anything else to that line.

Thanks for the fast answer. I didn't know that, thanks for explaining! Would it then be possible to remove the whole line?
Something like `"useTotalTime": false` ?

**Comment by phineas05** [comment]
Done. Update your copy of the script and set `display` -> `hideTotalTime` to `true`  in your config.

**Comment by zeroquinc** [comment]
> Done. Update your copy of the script and set `display` -> `hideTotalTime` to `true` in your config.

Thank you kind sir!
