### ISSUE TITLE
Connecting to Plex Media Server

### ISSUE THREAD

**Issue by 2ndwonder** [phineas05/discord-rich-presence-plex#55]
Hi

Trying to connect to Plex but it keeps hanging on ''Connecting to Plex Media Server''
Can't make a handshake. did I miss something?

<img width="717" alt="image" src="https://user-images.githubusercontent.com/24813161/189626199-f863c88b-46ce-462a-a380-35809420b845.png">

**Comment by phineas05** [comment]
Refer to #41.

**Comment by 2ndwonder** [comment]
Fixed thank you
