### ISSUE TITLE
Doesn't work with Ubuntu Budgie 18.04.1

### ISSUE THREAD

**Issue by mcpasta** [Phineas05/discord-rich-presence-plex#7]
I've used both Stable and PTB versions of discord but with no avail, the client doesn't pick up the rich presence at all. 
While checking the console, this error code seems to show up everytime a music/video starts playing.
`onPlexServerAlert Error: There is no current event loop in thread 'Thread-5'.`

**Comment by Phineas05** [comment]
Are you using the latest version of Python?

**Comment by mcpasta** [comment]
Hi, I have 2 versions installed 
python - python 2.7.15
and
python3 - python 3.6.5

When I launch the script, I always go for `python3 ./discordRichPresencePlex.py`

**Comment by mcpasta** [comment]
![screenshot from 2018-08-09 15 46 47](https://user-images.githubusercontent.com/30278742/43885512-ad390a7a-9beb-11e8-834a-556160f4c450.png)

**Comment by Phineas05** [comment]
I've just updated the script. Update your copy and let me know if it's fixed.

**Comment by mcpasta** [comment]
Perfect! that's working for me! Thanks!1
