### ISSUE TITLE
Not working on OSX

### ISSUE THREAD

**Issue by knackrack615** [Phineas05/discord-rich-presence-plex#8]
For some reason i cant get the script to interact with discord at all

It connects to Plex and gets the current playing data just fine.. but thats all it does

![image](https://user-images.githubusercontent.com/2822335/44291800-757ac700-a289-11e8-9a9d-8f3ef56c6a17.png)

**Comment by Phineas05** [comment]
Does the script just stop there?

**Comment by knackrack615** [comment]
It will repeat the last line as long as something is playing but that's it,
it doesn't do anything else

**Comment by knackrack615** [comment]
I've added you on discord, hmu if you want so we can troubleshoot it :)

Knackrack615#1337

**Comment by knackrack615** [comment]
We ended up figuring out what the issue was, apparently the latest version of websocket-client broke something in plexapi and it no longer connects properly.

For anyone having the same issue install websocket-client version 0.48.0
